# Generated by Django 4.1.4 on 2022-12-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
