# Generated by Django 4.1.4 on 2023-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
