# Generated by Django 4.1.4 on 2022-12-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=250)),
                ('subject_id', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
            ],
        ),
    ]
